version: "3"

services:
  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
  server:
    build: ./server
    environment:
      TV_MEDIA_DIRECTORY: /movies
    expose:
      - "3000"
    volumes:
      - ${TV_MEDIA_DIRECTORY}:/movies:ro
