version: "3"

services:
  client:
    build: ./client
    environment:
      SERVER_HOST: ${SERVER_HOST}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
  server:
    build: ./server
    environment:
      TV_MEDIA_DIRECTORY: /movies
    ports:
      - "3000:3000"
    volumes:
      - ${TV_MEDIA_DIRECTORY}:/movies:ro
